repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: frontend-eslint
        name: frontend-eslint
        entry: bash -lc 'cd frontend && npm run lint'
        language: system
        pass_filenames: false
        files: ^frontend/.*\.(js|jsx)$

-   repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
    -   id: black
